insert into country values (1,'Papua New Guinea');
insert into country values (2,'Greenland');
insert into country values (3,'Iceland');
insert into country values (4,'Canada');
insert into country values (5,'Algeria');
insert into country values (6,'Benin');
insert into country values (7,'Burkina Faso');
insert into country values (8,'Ghana');
insert into country values (9,'Cote d Ivoire');
insert into country values (10,'Nigeria');
insert into country values (11,'Niger');
insert into country values (12,'Tunisia');
insert into country values (13,'Togo');
insert into country values (14,'Belgium');
insert into country values (15,'Germany');
insert into country values (16,'Estonia');
insert into country values (17,'Finland');
insert into country values (18,'United Kingdom');
insert into country values (19,'Guernsey');
insert into country values (20,'Jersey');
insert into country values (21,'Isle of Man');
insert into country values (22,'Falkland Islands');
insert into country values (23,'Netherlands');
insert into country values (24,'Ireland');
insert into country values (25,'Denmark');
insert into country values (26,'Faroe Islands');
insert into country values (27,'Luxembourg');
insert into country values (28,'Norway');
insert into country values (29,'Poland');
insert into country values (30,'Sweden');
insert into country values (31,'South Africa');
insert into country values (32,'Botswana');
insert into country values (33,'Congo (Brazzaville)');
insert into country values (34,'Congo (Kinshasa)');
insert into country values (35,'Swaziland');
insert into country values (36,'Central African Republic');
insert into country values (37,'Equatorial Guinea');
insert into country values (38,'Saint Helena');
insert into country values (39,'Mauritius');
insert into country values (40,'British Indian Ocean Territory');
insert into country values (41,'Cameroon');
insert into country values (42,'Zambia');
insert into country values (43,'Comoros');
insert into country values (44,'Mayotte');
insert into country values (45,'Reunion');
insert into country values (46,'Madagascar');
insert into country values (47,'Angola');
insert into country values (48,'Gabon');
insert into country values (49,'Sao Tome and Principe');
insert into country values (50,'Mozambique');
insert into country values (51,'Seychelles');
insert into country values (52,'Chad');
insert into country values (53,'Zimbabwe');
insert into country values (54,'Malawi');
insert into country values (55,'Lesotho');
insert into country values (56,'Mali');
insert into country values (57,'Gambia');
insert into country values (58,'Spain');
insert into country values (59,'Sierra Leone');
insert into country values (60,'Guinea-Bissau');
insert into country values (61,'Liberia');
insert into country values (62,'Morocco');
insert into country values (63,'Senegal');
insert into country values (64,'Mauritania');
insert into country values (65,'Guinea');
insert into country values (66,'Cape Verde');
insert into country values (67,'Ethiopia');
insert into country values (68,'Burundi');
insert into country values (69,'Somalia');
insert into country values (70,'Egypt');
insert into country values (71,'Kenya');
insert into country values (72,'Libya');
insert into country values (73,'Rwanda');
insert into country values (74,'Sudan');
insert into country values (75,'South Sudan');
insert into country values (76,'Tanzania');
insert into country values (77,'Uganda');
insert into country values (78,'Albania');
insert into country values (79,'Bulgaria');
insert into country values (80,'Cyprus');
insert into country values (81,'Croatia');
insert into country values (82,'France');
insert into country values (83,'Saint Pierre and Miquelon');
insert into country values (84,'Greece');
insert into country values (85,'Hungary');
insert into country values (86,'Italy');
insert into country values (87,'Slovenia');
insert into country values (88,'Czech Republic');
insert into country values (89,'Israel');
insert into country values (90,'Malta');
insert into country values (91,'Austria');
insert into country values (92,'Portugal');
insert into country values (93,'Bosnia and Herzegovina');
insert into country values (94,'Romania');
insert into country values (95,'Switzerland');
insert into country values (96,'Turkey');
insert into country values (97,'Moldova');
insert into country values (98,'Macedonia');
insert into country values (99,'Gibraltar');
insert into country values (100,'Serbia');
insert into country values (101,'Montenegro');
insert into country values (102,'Slovakia');
insert into country values (103,'Turks and Caicos Islands');
insert into country values (104,'Dominican Republic');
insert into country values (105,'Guatemala');
insert into country values (106,'Honduras');
insert into country values (107,'Jamaica');
insert into country values (108,'Mexico');
insert into country values (109,'Nicaragua');
insert into country values (110,'Panama');
insert into country values (111,'Costa Rica');
insert into country values (112,'El Salvador');
insert into country values (113,'Haiti');
insert into country values (114,'Cuba');
insert into country values (115,'Cayman Islands');
insert into country values (116,'Bahamas');
insert into country values (117,'Belize');
insert into country values (118,'Cook Islands');
insert into country values (119,'Fiji');
insert into country values (120,'Tonga');
insert into country values (121,'Kiribati');
insert into country values (122,'Wallis and Futuna');
insert into country values (123,'Samoa');
insert into country values (124,'American Samoa');
insert into country values (125,'French Polynesia');
insert into country values (126,'Vanuatu');
insert into country values (127,'New Caledonia');
insert into country values (128,'New Zealand');
insert into country values (129,'Antarctica');
insert into country values (130,'Afghanistan');
insert into country values (131,'Bahrain');
insert into country values (132,'Saudi Arabia');
insert into country values (133,'Iran');
insert into country values (134,'Jordan');
insert into country values (135,'West Bank');
insert into country values (136,'Kuwait');
insert into country values (137,'Lebanon');
insert into country values (138,'United Arab Emirates');
insert into country values (139,'Oman');
insert into country values (140,'Pakistan');
insert into country values (141,'Iraq');
insert into country values (142,'Syria');
insert into country values (143,'Qatar');
insert into country values (144,'Northern Mariana Islands');
insert into country values (145,'Guam');
insert into country values (146,'Marshall Islands');
insert into country values (147,'Midway Islands');
insert into country values (148,'Micronesia');
insert into country values (149,'Palau');
insert into country values (150,'Taiwan');
insert into country values (151,'Japan');
insert into country values (152,'South Korea');
insert into country values (153,'Philippines');
insert into country values (154,'Argentina');
insert into country values (155,'Brazil');
insert into country values (156,'Chile');
insert into country values (157,'Ecuador');
insert into country values (158,'Paraguay');
insert into country values (159,'Colombia');
insert into country values (160,'Bolivia');
insert into country values (161,'Suriname');
insert into country values (162,'French Guiana');
insert into country values (163,'Peru');
insert into country values (164,'Uruguay');
insert into country values (165,'Venezuela');
insert into country values (166,'Guyana');
insert into country values (167,'Antigua and Barbuda');
insert into country values (168,'Barbados');
insert into country values (169,'Dominica');
insert into country values (170,'Martinique');
insert into country values (171,'Guadeloupe');
insert into country values (172,'Grenada');
insert into country values (173,'Virgin Islands');
insert into country values (174,'Puerto Rico');
insert into country values (175,'Saint Kitts and Nevis');
insert into country values (176,'Saint Lucia');
insert into country values (177,'Aruba');
insert into country values (178,'Netherlands Antilles');
insert into country values (179,'Anguilla');
insert into country values (180,'Trinidad and Tobago');
insert into country values (181,'British Virgin Islands');
insert into country values (182,'Saint Vincent and the Grenadines');
insert into country values (183,'Kazakhstan');
insert into country values (184,'Kyrgyzstan');
insert into country values (185,'Azerbaijan');
insert into country values (186,'Russia');
insert into country values (187,'Ukraine');
insert into country values (188,'Belarus');
insert into country values (189,'Turkmenistan');
insert into country values (190,'Tajikistan');
insert into country values (191,'Uzbekistan');
insert into country values (192,'India');
insert into country values (193,'Sri Lanka');
insert into country values (194,'Cambodia');
insert into country values (195,'Bangladesh');
insert into country values (196,'Hong Kong');
insert into country values (197,'Laos');
insert into country values (198,'Macau');
insert into country values (199,'Nepal');
insert into country values (200,'Bhutan');
insert into country values (201,'Maldives');
insert into country values (202,'Thailand');
insert into country values (203,'Vietnam');
insert into country values (204,'Burma');
insert into country values (205,'Indonesia');
insert into country values (206,'Malaysia');
insert into country values (207,'Brunei');
insert into country values (208,'East Timor');
insert into country values (209,'Singapore');
insert into country values (210,'Australia');
insert into country values (211,'Christmas Island');
insert into country values (212,'Norfolk Island');
insert into country values (213,'China');
insert into country values (214,'North Korea');
insert into country values (215,'Mongolia');
insert into country values (216,'United States');
insert into country values (217,'Latvia');
insert into country values (218,'Lithuania');
insert into country values (219,'Armenia');
insert into country values (220,'Eritrea');
insert into country values (221,'Palestine');
insert into country values (222,'Georgia');
insert into country values (223,'Yemen');
insert into country values (224,'Bermuda');
insert into country values (225,'Solomon Islands');
insert into country values (226,'Nauru');
insert into country values (227,'Tuvalu');
insert into country values (228,'Namibia');
insert into country values (229,'Djibouti');
insert into country values (230,'Montserrat');
insert into country values (231,'Johnston Atoll');
insert into country values (232,'Western Sahara');
insert into country values (233,'Niue');
insert into country values (234,'Cocos (Keeling) Islands');
insert into country values (235,'Myanmar');
insert into country values (236,'Svalbard');
insert into country values (237,'Wake Island');
